# Resume Configuration

#Config Notes:
#   Defaults listed after each option show settings for generating a normal, base, resume.


# TARGET: Change which Resume I am generating by replacing the second item with the target
# directory. This will change where the index.html page is sourced while still allowing
# access to all the directories in root.
include: 
- _resumes
- _testResume    # Target


# DEFAULT STYLESHEET: for standard resumes. This is usually STATIC but this option allows 
# me to switch to updated defaults with deleting the previous one.
# This file is ALWAYS in the root _sass directory, and is included without extension, 
# e.g. "defaultStyle.scss" is included as "default-style: defaultStyle".
default-style: defaultStyle


# CHANGE STYLE: Change resume style from just using the default stylesheet (see above setting) 
# to either replace default stylesheet or add extra stylesheets to default stylesheet.

# The "load_paths" option allows me to use different locations for my stylesheets, but 
# does not change what will load, that is done by the "assets/css/styles.scss" file's 
# @include statements. 
# If no additional style needed, comment out "load_paths" option.
sass:
  load_paths: [_resumes/_testResume/_sass]    # default: load_paths: []
  sass_dir: _sass    # STATIC
  style: compressed    # STATIC

# These options set what stylesheets are used for the resume by setting the @imports in 
# the "styles.scss" file. 
#  DEFAULT: If both are set to to false only the default stylesheet will be used for the resume.
#  Option 1: The "replace_default_style" adds to @imports full "style_list" given below but 
#  NOT the "defaultStyle".
#  Option 2: The "additional_styles" adds to @imports full "style_list" AND the "defaultStyle".
# NOTE: only one of these should be set to "true" 
replace_default_style: false    # default: false
additional_styles: true    # default: false

# If one of above options is set to "true" this list will be added to the @includes of the 
# "styles.scss" file. 
# Note: the filename is the name of each additional stylesheet, minus the extension, I want 
# to include, be they from the root _sass directory, or one of the resumes' _sass directories, 
# e.g. to testStyle.scss is included as "- {filename: testStyle}".
style_list: 
- {filename: testStyle}

###############################################################################
# STATIC CONFIG (i.e. items that should never need to be changed) 

# Front Matter Defaults 
#   Note: scope "_resumes/" and permalink "/" are what allow target directory to be a 
#   directory in _resumes. Without these it does not work.  
defaults:
 -
   scope:
     path: _resumes/
   values:
     permalink: /  
     layout: defaultLayout
     stylesheet: /assets/css/styles.css
     
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.



# Build settings

