### Base Config File ###
# This base _config.yml file is included in all resumes.
# Config Notes:
#    "DEFAULT VALUES" listed before each config variable show settings for generating a 
#     resume with default contents.
#    "STATIC" marked config variables should NOT be changed.

###############################################################################
# STATIC CONFIG OPTIONS:
# All config variables in below section should never need to be changed.

# Base Front Matter Defaults:
#   Note: scope "_resumes/" and permalink "/" are what allow a Resume's Source Directory to be 
#   in the "_resumes" directory instead of the usual Jekyll Source Directory location 
#   in Root.
defaults:
 -
   scope:
     path: _resumes/
   values:
     permalink: /  
     layout: defaultLayout
     stylesheet: /assets/css/styles.css

###############################################################################