- platform: GitHub
  name: ZLJett 
  link: https://github.com/ZLJett
  class: icon-github
- platform: LinkedIn
  name: Zachariah Jett
  link: https://www.linkedin.com/in/zachariahjett/
  class: icon-linkedin